# This is the network config written by 'subiquity'
network:
  version: 2
  ethernets:
    enp0s8:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.10.11/24 #NODE_IP_SW: it exploits VBOX inet switch