network:
  version: 2
  ethernets:
    enp0s9:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.21.10/24 #NODE_IP_RTR: connection is routed to the router VM
      routes:
        - to: 192.168.0.0/24 #Relegate enp0s9 route to private network. Otherwise (using default), you'll override NAT metric to internet
          via: 192.168.21.1